---
title: "BD final project"
author: "吳睿芸"
date: "2024-06-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Regression

```{r}
library(mlba)
library(caret)
car.df <- mlba::ToyotaCorolla
car.df
```

# data
```{r}
# select variables for regression
outcome <- "Price"
predictors <- c("Age_08_04", "KM", "Fuel_Type", "HP", "Met_Color", "Automatic",
                "CC", "Doors", "Quarterly_Tax", "Weight")
# reduce data set to first 1000 rows and selected variables
car.df <- car.df[1:1000, c(outcome, predictors)]

# Take a look at the data
str(car.df)

# partition data
set.seed(1)  # set seed for reproducing the partition
idx <- caret::createDataPartition(car.df$Price, p=0.6, list=FALSE)
train.df <- car.df[idx, ]
train.df
holdout.df <- car.df[-idx, ]
holdout.df
```

## lm()
```{r}
# use lm() to run linear regression of Price on all 11 predictors in the training set
# use . after ~ to include all the remaining columns in train.df as predictors
car.lm <- lm(Price ~ ., data = train.df)
#  use options() to ensure numbers are not displayed in scientific notation
options(scipen = 999)
summary(car.lm)
```

## 我們的資料
```{r}
library(skimr)
library(magrittr)
library(ggplot2)
library(caret)
library(corrplot)
library(dplyr)
library(mice)

Data<- read.csv("C:/Users/user/Downloads/data/data.csv", header = TRUE, as.is = TRUE, encoding = "UTF-8")
```

```{r}
rownames(Data)=Data[,1]
Data=Data[,-1]
Data=Data[,-1]
head(Data)

f4=apply(Data[,1:5],1,function(x) all(!is.na(x)))
#f4=apply(Data,1,function(x) all(!is.na(x)))
Data=Data[f4==TRUE,]
miss=apply(Data,1,function(x) sum(is.na(x)))
Data=Data[miss<=4,]
Data=Data[Data$學歷!=4,]
Data=complete(mice(Data,method = 'pmm',m=5,seed=500))
```


```{r}
A1=apply(Data[,6:10],1,function(x) mean(x))
A2=apply(Data[,11:15],1,function(x) mean(x))
A3=apply(Data[,16:20],1,function(x) mean(x))
A4=apply(Data[,21:25],1,function(x) mean(x))
A5=apply(Data[,26:30],1,function(x) mean(x))
A=apply(Data[,6:30],1,function(x) mean(x))
B1=apply(Data[,31:35],1,function(x) mean(x))
B2=apply(Data[,36:40],1,function(x) mean(x))
B3=apply(Data[,41:45],1,function(x) mean(x))
B4=apply(Data[,46:50],1,function(x) mean(x))
B=apply(Data[,31:50],1,function(x) mean(x))
Data=data.frame(Data, A1)
Data=data.frame(Data, A2)
Data=data.frame(Data, A3)
Data=data.frame(Data, A4)
Data=data.frame(Data, A5)
Data=data.frame(Data, B1)
Data=data.frame(Data, B2)
Data=data.frame(Data, B3)
Data=data.frame(Data, B4)
Data=data.frame(Data, A)
Data=data.frame(Data, B)
Data$A = Data$A

corrplot(cor(data.frame(Data[, 1:5],Data[, 51:61])), method="square",addCoef.col = "grey")

Data |> ggplot() +geom_point(aes(x=B4, y=A1) ) 

model <- lm(B4 ~ A1 + A2 + A3 + A4 + A5, data = Data)
summary(model)

```
```{r}
ggplot(Data, aes(x = A2, y = B4)) +
  geom_point() +  # 繪製數據點
  geom_smooth(method = "lm", se = FALSE) +  # 繪製回歸線，不顯示標準誤差帶
  labs(title = "Linear Regression of B4 on A2",
       x = "A2",
       y = "B4") +
  theme_minimal()
```

